server:
  port: 8082

spring:
  application:
    name: ms-courier

  datasource:
    url: jdbc:postgresql://localhost:5432/courier_db
    username: postgres
    password: 12345
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  liquibase:
    change-log: classpath:db/db.changelog-master.yaml
